version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    networks:
      - jura-net

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - jura-net

networks:
  jura-net:
    driver: bridge
